services:
  scanoss:
    build:
      context: .
    volumes:
      - /data/test-docker/ldb:/var/lib/ldb
      - /data/test-docker/tmp/shm:/dev/shm
      - /data/test-docker/tmp:/temp
    tty: true
    ports:
      - 4443:4443
